site_name: Anastasia's Docs
site_description: Anastasia's Docs
repo_url: https://github.com/kichukowa
edit_uri: ""
site_dir: dist

nav:
  - Home: index.md
  - Markdown Cheatsheet in .md file: demo-md.md
  - Jupyter Notebook Markdown: demo-nb-md.ipynb
  - Jupyter Notebook Cells: demo-nb.ipynb
  - A .py file (jupytext): demo-script.py
  - Demo - Ruby Notebook: ruby.ipynb
  - Demo - Variational inference nb: variational-inference-nb.ipynb
  - Demo - Variational inference script: variational-inference-script.py
  - Cheatsheets:
      - Python Cheatsheet: python-cheatsheet.md
      - Pandas Cheatsheet: pandas_cheatsheet.ipynb

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
  palette:
    - scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed
  - toc:
      permalink: true

plugins:
  - search
  - mkdocs-jupyter:
      execute: false
      include_requirejs: true

extra:
  analytics:
    provider: google
    property: G-3673QMK9C4
