site_name: Nencho's Docs
site_description: Nencho's Docs
repo_url: https://github.com/nzahariev
edit_uri: ""
site_dir: dist

nav:
  - Home: index.md
  - Python:
      - Python Fundamentals: python-cheatsheet.md
      - Pandas Fundamentals: pandas_cheatsheet.ipynb
  - Containers:
      - Kubernetes: kubernetes.md
      - Docker: docker.md
  - Linux:
      - Linux Commands: linux.md
      - Bash Scripting: bash.md
      - Unix Text Processing: unix-text.md
  - Cloud:
      - AWS CLI: aws.md
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
  palette:
    - scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed
  - toc:
      permalink: true

plugins:
  - search
  - mkdocs-jupyter:
      execute: false
      include_requirejs: true

extra:
  analytics:
    provider: google
    property: G-3673QMK9C4
