name: Build and Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: sudo git config --system --add safe.directory $GITHUB_WORKSPACE
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.13
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: sudo pip install mkdocs-jupyter
      - run: sudo mkdocs gh-deploy --force